### ISSUE TITLE
Display metrics per month

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#100]

**Comment by rushirajnenuji** [comment]
Usage statistics ARE reported on monthly intervals aligned with calendar months, not months from publication date.
-	The system has Aggregated usage report for all versions of a dataset: Total_Dataset_Investigations, Unique_Dataset_Investigations, Total_Dataset_Requests, and Unique_Dataset_Requests.
-	Develop a view to generate the graphs over time to display this usage metrics for the dataset requested by the user.
-	TODO: Decide how to display the metrics for different versions.

**Comment by mfenner** [comment]
DataCite Event Data API shows usage stats and citations broken down by year and month.

**Comment by rushirajnenuji** [comment]
DataONE update: Displaying metrics per month for dataset landing page has been implemented along with time-series chart with the releases [MetacatUI v2.1.0](https://github.com/NCEAS/metacatui/releases/tag/2.1.0) and [MetacatUI v2.2.0](https://github.com/NCEAS/metacatui/releases/tag/2.2.0)
