### ISSUE TITLE
Display citations

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#102]

**Comment by rushirajnenuji** [comment]
Develop a view to display the citations count for each component individually.
-	The citations for the entire dataset would be the summation of the citations count of the dataset as well as the citations count of each individual component of the dataset.
-	TODO: Decide how to display the citations for different versions.

**Comment by mbjones** [comment]
For now, citation information is available from the DataCite.CrossRef EventData API.  There are only a few thousand total citations in the system, but some can be found where journal articles cite data in DataONE repositories.  Here's an example query that finds all (currently 8) citations to data in the KNB that has been assigned a DOI with prefix 10.5063:

https://api.eventdata.crossref.org/v1/events/scholix?source=crossref&obj-id.prefix=10.5063

There are quite a few more citations to Dryad data.

Full documentation for the EventData API is here:
https://www.eventdata.crossref.org/guide/service/query-api/

**Comment by rushirajnenuji** [comment]
Solved with : 
- [Display MDC usage and citation counts on landing pages](https://github.com/NCEAS/metacatui/issues/594), 
- [Create Metric view](https://github.com/NCEAS/metacatui/issues/597),  
- [Create Metric Model](https://github.com/NCEAS/metacatui/issues/598) and
- [Add functionality to add Citations information](https://github.com/DataONEorg/metrics-service/issues/8)
