### ISSUE TITLE
Display on landing page

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#107]

**Comment by rushirajnenuji** [comment]
Develop a view that displays the content for the entire dataset.
-	This includes:
o	Summarized Data level metrics form the entire dataset.
o	Data level metrics for the individual dataset components.
o	Graphs for the time series for the metrics of this dataset.
o	TODO: Decide the location for this time series graphs.
o	Details / briefs about each individual components for the dataset.

**Comment by rushirajnenuji** [comment]
Solved with : 
- [Display MDC usage and citation counts on landing pages](https://github.com/NCEAS/metacatui/issues/594), 
- [Create Metric view](https://github.com/NCEAS/metacatui/issues/597),  and
- [Create Metric Model](https://github.com/NCEAS/metacatui/issues/598)
