### ISSUE TITLE
mockup display UI

### ISSUE THREAD

**Issue by mbjones** [CDLUC3/Make-Data-Count#117]
Revise existing mockups to incorporate fewer DLM stats, and refine the features. This includes:

- [x] remove save stats
- [x] remove social media stats
- [x] add volume metrics
- [x]  color scheme
- [x] fix time series plots for longer display periods

**Comment by rushirajnenuji** [comment]
TODO: decide an appropriate color scheme for the icons.

**Comment by rushirajnenuji** [comment]
Meeting discussion (12/07/2017): Modify the mockups for the metadata view by adding the stats layered horizontally. Design the modal view functionality to display graphs to the user.  Generate InVision project to get interactive set of mockups.

- Make the icons smaller by ~ 25%

**Comment by csjx** [comment]
Just to clarify the location we discussed today: Until we incorporate a sidebar into the `MetadataView` like we  have in the `EditorView`, let's plan on a more horizontal layout like Lauren's original. Here's a low-fi sketch of the approximate location:
<img width="1334" alt="metadata-view-metrics-summaries" src="https://user-images.githubusercontent.com/1437565/33748255-a8b166f0-db84-11e7-8764-51b23f773b91.png">
We also had decided last week that the time series graphs will be displayed in a modal from this particular view, and the modal is activated by clicking on the particular metric summary. The summaries need to give visual feedback on `hover` to indicate that they are clickable, so the mockups should reflect this.  We also discussed having a tooltip on `hover` to give help on the metric itself.  The mockups should reflect this as well.

**Comment by rushirajnenuji** [comment]
Landing Page view interactive mockup : https://invis.io/DNEX3A7HU

**Comment by rushirajnenuji** [comment]
Changes to the mockups ()
- Landing page : Change citations mock-up icon.
- Search View : get rid of the pop ups in citation list.
- Search View : icon color same as dataone maroon color.
- CitationGraph: Bootstrap modal view and citation list.
- DownloadsGraph: Bootstrap modal, bar chart
- ViewsGraph: Bootstrap modal, bar chart
- UserProfile: Citations icon to Quotations icon
- UserProfile: Views bar chart, legend on both axis for graphs.
- UserProfile : Take out citations line chart, use the current dataone user profile.
- UserProfile: Remove doughnut charts.

**Comment by rushirajnenuji** [comment]
# Meeting discussion: (12/21/2017)

##### Suggested Feedback on UI
- Add description to the `User Profile` for the `views` section, and make the title `font-size` consistent with other sections of the user profile.
- Make the modal content similar to the `Time period of the Data` content of the User profile.
- At the top of the statistics and the figures, section add a citation graph (possibly a line chart) and a list of citations for all the datasets of the specific user. This should be a scrollable list of citations for the user.

##### Important Points to discuss:
- The decision needs to be based on the versioning.
	- To be specific the versioning should be in the terms of the dataset, users and the repository. There could be different finalized versioning for different entities (i.e. datasets/users/ repository)
- In the user profile view's section, do we need to have investigations and requests both for the data and metadata separately?
	- Matt: "Think of this I terms of a 2x2 matrix, with the legends on the x-axis as the investigations and the requests and the legends on the y-axis as data and metadata. We need to decide whether all 4 cells make sense and are useful (or not?)"	
- Currently, the charts/graphs are based on Lauren Walker's implementation using the `d3.js` library. Matt wants graphs to have capabilities to be able to zoom in.
	- Chris's suggested: "Using Google charts (might need more research?!)"

##### Swagger YAML documentation:
- We removed all the 4 models for metrics and created a generalized metric model. This will be helpful in the future if we want to add metrics. (see documentation 1.0.0.2)
	- Added a property: `location` along with the `counts by date` array object.
- Matt's suggestion: create an additional API end-point for the summaries (possibly `/metricsSummaries/{id}`), this will be helpful for the user profile and the repo profile view pages to get the summaries
	- Chris's suggestion: "Add a Metric type (volume / citation / investigation / requests) and Metric Category (Contributor / funder / repository / award-number). Use this to extend the API 1.0.0.2 that we created after this particular MDC call."

**Comment by mbjones** [comment]
Current mockups are here: https://projects.invisionapp.com/share/7MFRHSL6WZT#/278315639_LandingPage
