### ISSUE TITLE
generate list of API needs from UI mockups

### ISSUE THREAD

**Issue by mbjones** [CDLUC3/Make-Data-Count#118]
Once the UI mockups are in progress, we can use those to design the queries that will be necessary to drive the API.  This will include knowledge of grouping facets and aggregation needs.  We can use the analysis to determine:

- what fields are needed in the usage and citation APIS
- what filter queries are needed
- what aggregations are needed
- performance requirements for a responsive UX

**Comment by rushirajnenuji** [comment]
Meeting discussion (12/07/2017): Think of what information should be stored on the Client side. What would be the best way to store that information: whether to extend a model or develop a new model. Based on these details, design high-level technical diagrams for the Client side of the system.

**Comment by rushirajnenuji** [comment]
@csjx , @laurenwalker  and I, during weekly MDC meeting on 12/14/201, decided that we'll be using a REST API method `all()` that would be requesting for all data metrics from the HUB for a given PID. This would include the summary of data metrics as well as a collection of individual metric objects including a timestamp for that particular metric event. We initially have come up with a basic Data Metric Model which can be found [here](https://github.com/CDLUC3/Make-Data-Count/blob/master/dev-notes/DataMetricsAPI.yaml)

**Comment by kjgarza** [comment]
Brigning  usage and citation together is not trivial. Could we do  (2) separate callsfor MVP? See January 22th Notes: https://docs.google.com/document/d/1b7DAVm2Oqash2pF9vhLG1gN31TxtcHGF8L1vmjF8VZM/edit#
