### ISSUE TITLE
Registration process for new API clients

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#12]

**Comment by kjgarza** [comment]
![Bildschirmfoto 2018-07-30 um 14.12.03.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5936775a17ad63001a910f29/125516c66e82c728ace21e0d46ca9d96279180a186fbb245ab49ffd47b16762b6454f46623d5a33db2022a55415e4cb2415b4d58eeb9cb74fce36f34985619e8d83e5f77943d10acebd64cbd06ba208f1a8ce0e8821fc5fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e3445da1123f61e171346e0a.png)

**Comment by kjgarza** [comment]
DataCite Users would need to Loging with Client Credentials and then can get their token generated. We could do this from DOI Fabrica.

Other Users, would need a different approach.

**Comment by kjgarza** [comment]
put on hold as Datacite is changing all authenthication . details in https://github.com/datacite/sashimi/issues/39

**Comment by kjgarza** [comment]
The work DataCite is down in authenthication is going to run for a couple more months, hence we won't be completing the automated process for registering hub provider until after June. For the moment, we will make a clearer the worklow to obtain credentials in our documentation. https://github.com/CDLUC3/Make-Data-Count/issues/140
