### ISSUE TITLE
Generate Class diagrams

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/Make-Data-Count#120]
With reference to issue #118 generate high-level Class diagrams for client-side.
Tools: PlantUML.

**Comment by rushirajnenuji** [comment]
It seems that we've finished this based on the [commit](https://github.com/DataONEorg/metrics-service/commit/36db74f7ee317f08b6755a2045265936448f669a)

[URL for the file](https://github.com/DataONEorg/metrics-service/blob/dev-1.0/doc/class-diagram.rst)

@csjx  - Could you please review this. Thanks!

**Comment by mbjones** [comment]
Rushi, the diagram looks good.  Have you been keeping it up do date as the metrics application is implemented?  Are all of the classes represented?  And are their names/attributes accurate?  If so, then I think we can close this one.
