### ISSUE TITLE
Usability test for MVP mockups

### ISSUE THREAD

**Issue by mbjones** [CDLUC3/Make-Data-Count#124]
Conduct usability tests with mockups.  Use an InVision prototype. Develop questions for usability testers in this ticket.

**Comment by rushirajnenuji** [comment]
Link to the MockUps: https://invis.io/7MFRHSL6WZT#/278315639_LandingPage

Potential Questions: 
* `Dataset Landing page`: How would you check the `detailed download information` about the dataset?
* `Downloads modal window`: How would you navigate from the `downloads` modal window to the `view` modal window?
* `User profile page`: How would you check detailed `usage stats` for the given user?
* `User profile page`: Interpret the usage stats for the `first` and the `fourth` dataset for the given user.

**Comment by mbjones** [comment]
At this point its probably better to test live systems, and maybe some mockups for features still to be implemented.  I wrote to Tennessee to set up a time to plan the tests.  Will report more here as details emerge.

**Comment by rushirajnenuji** [comment]
Part of #131 
In progress
