### ISSUE TITLE
Documentation about DataONEs approach to standardizing usage metrics

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#128]
Clear documentation about how repositories that aren't starting with raw logs can standardize usage metrics (and put into proper report format)

**Comment by rushirajnenuji** [comment]
Discussed in today's MDC meeting (August 08, 2018) that I'll be penning out our architecture and the workflow of our implementation.

**Comment by rushirajnenuji** [comment]
DataONE documentation available at: https://dataone-metrics-service.readthedocs.io/en/latest/index.html

@mbjones - This ticket is up for review.
