### ISSUE TITLE
Hub accepts CSV

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#130]

**Comment by kjgarza** [comment]
Merged with a different internal DataCite initiative to have a Standalone backend service with optional frontend

**Comment by kjgarza** [comment]
We think we won't be implementing ingestion of CSV. We do see enough interest on submitting reports on CSV. And working on this would require resources that we need to use somewhere else. However, we will  still want to provide reports in CSV as an output. replace for issue: https://github.com/CDLUC3/Make-Data-Count/issues/139
