### ISSUE TITLE
Scanning citations for DataONE.

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/Make-Data-Count#136]
Approach:

Step 1: Search for all the id's that have `doi` keyword in them.

Step 2: Get common prefixes for those DOIs and query Crossref at `https://api.eventdata.crossref.org/v1/events/scholix?source=crossref&obj-id.prefix=ID`, where `ID` is the DOI prefix.

Step 3: Crossmatch with the results and save the Dataone Citations into the database.

The prefixes that we got from scanning are:
{'10.1873', '10.6085', '10.5066', '10.5061', '10.5065', '10.6073', '10.5063', '10.6067', '10.5072', '10.1575'}

Counts for each prefix:
'10.1873': 0
'10.6085': 0
'10.5066': 0
'10.5061': 426
'10.5065': 4
'10.6073': 26
'10.5063': 2
'10.6067': 0 
'10.5072': 0
'10.1575': 0

Detailed results could be found at this Github Gist: https://gist.github.com/rushirajnenuji/dc231e682a226aefadb65f476193557c

**Comment by rushirajnenuji** [comment]
With the current logic, we've missed the PANGEA ids. At present, Crossref returns about 305 citations for `PANGEA - 10.1594`.

Upon investigation, it looks like PANGEA datasets are not registered with ids as DOIs. But, I notice that their series id is a DOI string. Scanning series ids could help us retrieve these citations.

**Comment by mbjones** [comment]
@mfenner Flagging you on the details of citation queries.

**Comment by mbjones** [comment]
And @rushirajnenuji it would be interesting to try to understand whether several of our datasets that we know have been cited will show up in the results given our current tools.  I'd like to accumulate a short list of exemplar datasets that have been cited and see where that leads.  For example:

| Authors  | Repository | Dataset Identifier  | Cited by publication with identifier |  Journal |
|----------|------------|-------------------|-----------------------------------|----------|
| Couture et al. | KNB  | [doi:10.5063/F1T151VR](https://doi.org/doi:10.5063/F1T151VR) |  [doi:10.1371/journal.pone.0199789](https://doi.org/10.1371/journal.pone.0199789) | PLOS One |

Can you come up with some more, that span repositories and span journals?  I note that the Couture et al. example above is cited in the 'Data availability' section which PLOS recommends using.  I'd also look for some examples from KNB, PANGAEA, LTER, DRYAD, and others.

These will make good examples to evaluate, and will likely be of interest to @mfenner and @kjgarza . Thanks.

**Comment by kjgarza** [comment]
For that specific  Citation, the problem could be related to the way in which the citation was ingested by Crossref. 

One can see that plos has it in thereferences section (http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199789#references
) and Crossref has it in their metadata but as an `unstructure citation` (https://support.crossref.org/hc/en-us/articles/214844903-XML-query-examples):

> https://api.crossref.org/works/10.1371/journal.pone.0199789

```xml
key: "ref33",
unstructured: "Couture J. EVOS data archiving project results: data, code and output (2016) [Internet]. KNB Data Repository; 2018. <comment>doi: <ext-link xmlns:xlink="http://www.w3.org/1999/xlink" ext-link-type="uri" xlink:href="https://doi.org/10.5063/F1T151VR" xlink:type="simple">10.5063/F1T151VR</ext-link></comment>"
```

I need to confirm with crossref what happens with these unstrustructed citations.

**Comment by mbjones** [comment]
@kjgarza any news on what crossref does with these unstructured citations?
