### ISSUE TITLE
Add publisher-id type `urn` for the reports.

### ISSUE THREAD

**Issue by rushirajnenuji** [CDLUC3/Make-Data-Count#137]
Hi @kjgarza - I discussed the issue we were having with Dave and Chris during our weekly MDC DataONE dev meeting and we came to a conclusion that type `urn` makes the most sense for the reporting service for all of the DataONE reports.

However, I will keep on sending the reports right now with the default configuration that we agreed on and then, later on, I'll perform an update once the HUB starts supporting the `urn` type.

**Comment by kjgarza** [comment]
fixed in : https://github.com/datacite/sashimi/commit/45d44b5708b6e936a5e386178af926d267a3b1ac#diff-0fec21d6b6e6a9b90e27dd9e1393b392
