### ISSUE TITLE
Implement pilot

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#44]
DataCite preparing a Log processor  pilot

**Comment by kjgarza** [comment]
Implementation was completed in https://github.com/datacite/shiba-inu/milestone/2
Validated with DOI Resolution Logs: https://api.datacite.org/events?source-id=datacite-resolution
Documented at the moment in : https://github.com/datacite/shiba-inu

ToDo
- [ ] Validating the implementation with Usage Logs from Dash 
- [ ] Transfer Documentation to support website
