### ISSUE TITLE
Implement MDC feeds into repo front end

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#85]

**Comment by rushirajnenuji** [comment]
The data citation statistics will be managed by the SCHOLIX. Both the data usage stats and the data citation statistics will be into the Lagotto back-end (the HUB). Use the RESI API developed by the DataCite developers to query the Lagotto system.
o	This MDC data fetched from the back-end needs to be projected on the front-end
o	TODO: Decide on what to have as an intermediary cache. (Perhaps an OLAP cube).
