### ISSUE TITLE
Test integration w/ Hub

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#86]

**Comment by rushirajnenuji** [comment]
Once, the API is developed, use it to query the HUB. Use the API's methods to retrieve the stats and display these stats on the front-end.
-	The HUB, as well as the API, are currently in the development stage.
-	For the accuracy and proper functionality of the system, the front-end system needs to be developed such that it is compatible with the products that are currently in the development stage.
