### ISSUE TITLE
Initiate RDA WG: Usage Metrics

### ISSUE THREAD

**Issue by aebudden** [CDLUC3/Make-Data-Count#89]

**Comment by dlowenberg** [comment]
[ ] Daniella to get in touch with Anita De Waard - confirmation to co-lead Usage Metrics WG
[ ] Martin to get in touch with Adrian Burton
[ ] Martin, Daniella, John to talk with Todd C about Publishing Data IG
[ ] Daniella to submit WG proposal to RDA along with Anita and Adrian
[ ] After RDA has confirmed WG, send announcement to community to join
