### ISSUE TITLE
Recruit people for other advisory structures

### ISSUE THREAD

**Issue by aebudden** [CDLUC3/Make-Data-Count#90]

**Comment by dlowenberg** [comment]
- [x] Daniella to reach out to potential advisory board members
- [ ] Daniella to reply asking for names on site, Doodle of dates for Jan/Feb
- [ ]

**Comment by dlowenberg** [comment]
Mark Parsons, Josh Greenberg, Jennifer Lin, Carly Strasser, Rodrigo Costas accepted invite. Waiting on Phil & Jo
