### ISSUE TITLE
Display metadata views

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#91]

**Comment by rushirajnenuji** [comment]
Develop a view that displays the number of times the metadata was accessed by the user.
-	Typically, this is the count of the investigations made for a given dataset.
-	For this we need the focus on the following:
o	Total_Dataset_Investigations: Total number of times a dataset or information related to a dataset was accessed and the data volume in megabytes that was transferred. Repeat access filters are applied to these transactions. Investigations (counts and volume) are reported for each version of the Dataset and for the cumulative total across versions.
o	Unique_Dataset_Investigations: Number of datasets investigated in unique user-sessions. If investigations for multiple components of the same Dataset occur in the same user-session, only one “unique” activity MUST be counted for that Dataset. Investigations (counts and volume) are reported for each version of the Dataset and for the cumulative total across versions.

**Comment by rushirajnenuji** [comment]
Solved with : 
- [Display MDC usage and citation counts on landing pages](https://github.com/NCEAS/metacatui/issues/594), 
- [Create Metric view](https://github.com/NCEAS/metacatui/issues/597),  and
- [Create Metric Model](https://github.com/NCEAS/metacatui/issues/598)
