### ISSUE TITLE
Display downloads

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#93]

**Comment by rushirajnenuji** [comment]
Develop a view to display the number of times the dataset was downloaded or accessed.
-	Typically, this is the count of the investigations made for a given dataset.
-	For this we need the focus on the following:
o	Total_Dataset_Requests: Total number of times a dataset was retrieved (the content was accessed or downloaded in full or a section of it) and the data volume in megabytes that was transferred. Double-click filters applied. Requests (counts and volume) are reported for each version of the Dataset and for the cumulative total across versions.
o	Unique_Dataset_Requests: Number and data volume of datasets requested in unique user-sessions. If requests for multiple components of the same Dataset occur in the same user-session, only one “unique” activity MUST be counted for that Dataset. Requests (counts and volume) are reported for each version of the Dataset and for the cumulative total across versions.

**Comment by rushirajnenuji** [comment]
Solved with : 
- [Display MDC usage and citation counts on landing pages](https://github.com/NCEAS/metacatui/issues/594), 
- [Create Metric view](https://github.com/NCEAS/metacatui/issues/597),  and
- [Create Metric Model](https://github.com/NCEAS/metacatui/issues/598)
