### ISSUE TITLE
Display citation list

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#97]

**Comment by rushirajnenuji** [comment]
Develop a view to display the list of citations for each component individually.
-	The citations for the entire dataset would be the list of the citations of the dataset as well as the list of citations of each individual component of the dataset.
-	TODO: Decide how to display the citations list for different versions.

**Comment by dlowenberg** [comment]
CDL implemented (July, 2018)

**Comment by rushirajnenuji** [comment]
DataONE Implemented ([September 2018](https://github.com/NCEAS/metacatui/releases/tag/2.2.0))
