### ISSUE TITLE
Display views per dataset

### ISSUE THREAD

**Issue by dlowenberg** [CDLUC3/Make-Data-Count#98]

**Comment by rushirajnenuji** [comment]
Develop a view that displays the number of times the dataset was accessed by the user.
-	This would be the summation of the count of the individual investigations made for each component of a given dataset.
-	 TODO: Decide how to display the view for different versions.
-	 Possible approach: Display the aggregate views of the dataset till a given version requested by the user (or retrieved from the landing page)

**Comment by rushirajnenuji** [comment]
Solved with : 
- [Display MDC usage and citation counts on landing pages](https://github.com/NCEAS/metacatui/issues/594), 
- [Create Metric view](https://github.com/NCEAS/metacatui/issues/597),  and
- [Create Metric Model](https://github.com/NCEAS/metacatui/issues/598)
